### ISSUE TITLE
100km*100km grids

### ISSUE THREAD

**Issue by Tao-Liang** [macroecology/letsR#10]
Hey All,
 I want to built a 1008100km gird using lets.presab() function, what should do with the "resol = " Any tips are appreciate.
Bests,
Tao

**Comment by fabro** [comment]
Dear Tao, 

The option will depend on the projection/CRS of your dataset (shapefiles/point occurrences). If your data is unprojected (geographical coordinates in lat-long degrees, which is the most common one), then you could use "resol=1" (one degree lat-long, which is roughly 100km at the equator). But, if your data is projected, for example in Behrmann equal-area projection, then "resol=" should be in the units of that projection. In the case of the Behrmann projection, the units are meters; then for 100km: "resol=100000".
