### ISSUE TITLE
Please remove dependencies on **rgdal**, **rgeos**, and/or **maptools**

### ISSUE THREAD

**Issue by rsbivand** [macroecology/letsR#11]
This package depends on (depends, imports or suggests) **raster** and one or more of the retiring packages **rgdal**, **rgeos** or **maptools** (https://r-spatial.org/r/2022/04/12/evolution.html). Since **raster** `3.6.3`, all use of external FOSS library functionality has been transferred to **terra**, making the retiring packages very likely redundant. It would help greatly if you could remove dependencies on the retiring packages as soon as possible.

**Comment by rsbivand** [comment]
You will be aware, for example from:
https://r-spatial.org/r/2022/04/12/evolution.html,
https://r-spatial.org/r/2022/12/14/evolution2.html,
https://r-spatial.org/r/2023/04/10/evolution3.html and
https://rsbivand.github.io/csds_jan23/bivand_csds_ssg_230117.pdf and 
perhaps view https://www.youtube.com/watch?v=TlpjIqTPMCA&list=PLzREt6r1NenmWEidssmLm-VO_YmAh4pq9&index=1 
that `rgdal`, `rgeos` and `maptools` will be retired this
year, in October 2023.

letsR imports 'maptools', 'rgdal', 'rgeos' and uses rgdal::readOGR rgeos::gArea rgeos::gCentroid rgeos::gContains rgeos::gOverlaps as found by `pkgapi`, bulk imported packages in NAMESPACE, in multiple files. You need to read https://r-spatial.org/r/2023/04/10/evolution3.html and its suggestions to see how to substitute sf methods and functions for those currently used, for example in the diffs of ASDAR code. Please fix best by June, latest by October 2023.

**Comment by rsbivand** [comment]
@fabro @BrunoVilela See also https://r-spatial.org/r/2023/05/15/evolution4.html. Please take urgent steps to resolve this issue. No positive changes appear in the repository. Less than three months remain to retain this package on CRAN.

**Comment by BrunoVilela** [comment]
Done! Package is now updated. Thanks!
