### ISSUE TITLE
error with raster-dev

### ISSUE THREAD

**Issue by rhijmans** [macroecology/letsR#14]
With the dev version of "raster" (https://github.com/rspatial/raster) I now see, when checking "letsR"

```
  ══ Failed tests ════════════════════════════════════════════════════════════════
  ── Error ('test-lets_addvar.R:37:3'): lets.addvar works fine, multiple rasters ──
  Error in `lets.addvar(PAM, tempstack)`: The PAM object and the variable (raster) 
           should be in the same projection
  Backtrace:
      ▆
   1. └─letsR::lets.addvar(PAM, tempstack) at test-lets_addvar.R:37:2
 ```

This is because of changes in "raster" related to the changes in the "sp family" packages. sp::identicalCRS does not work well with Raster* objects any more. 

You now need to use `CRS(Raster*)` or you could use `terra::same.crs(x, y)`. But the best approach might be to use "terra" instead of "raster". 

Can you please fix this so that your package won't break when I submit "raster" to CRAN?

**Comment by rhijmans** [comment]
It would be great if this could get fixed and sent to CRAN.

**Comment by BrunoVilela** [comment]
The package has now been updated for the terra package. Thanks!
