### ISSUE TITLE
Problem with lets.addvar related to the resolution of the rasters

### ISSUE THREAD

**Issue by VirginiaMorera** [macroecology/letsR#3]
Hi, 

I think I might have found an issue with your function lets.addvar, although it might well be that I am not using it properly. I am using R version 3.2.2, and letsR version  2.4 downloaded from GitHub the 2016-03-14. 

The problem is that the resolution of the RasterLayer generated with my PresenceAbsence object is not an integer, neither is the resolution of the raster I want to add as a variable. Below the code that reproduces the error I am getting: 

````R
proj4  <- CRS("+proj=longlat +datum=WGS84 +ellps=WGS84 +towgs84=0,0,0")

xy <- matrix(data = rnorm (200, mean = 0, sd =1), nrow = 100, ncol = 2)
sp <- rep(c("SP1", "SP2"), 50)


presab <- lets.presab.points(xy = xy, species = sp, 
                             xmn = min(xy[,1]), xmx = max(xy[,1]), ymn = min(xy[,2]), ymx = max(xy[,2]),
                             resol = c(0.02, 0.02), crs = proj4, count = T)

library(raster)
r1 <- raster(nrow=10, ncol=10, res = c(0.016, 0.016), crs = proj4)
values(r1) <- runif(ncell(r1))
plot(r1)

presab2 <- lets.addvar(presab, r1, fun = mean)

Error in .local(x, ...) : fact should be > 1
````
I've done a bit of digging inside the function itself, and found out that is in the `aggregate` step that the error appears:
````R
if (projection(x[[2]]) != projection(y)) {
        stop("The PAM object and the variable (raster) \n         should be in the same projection")
    }
    var_c <- crop(y, x[[2]])
    res1 <- res(var_c)[1]
    res2 <- res(x[[2]])[1]
    if (res2 > res1) {
        var_a <- aggregate(var_c, fact = res2/res1, na.rm = TRUE, fun = mean)
````

Here, as my `res2 = 0.02` and my `res1 = 0.016`, `fact = res2/res1` is not an integer, and although it IS larger than 1, it throws an error. 

I figured, if you wrap the res2/res1 around a round(), a floor() or a ceiling() it might actually work. I have actually tried it myself and have been able to make it work re-runing the function step by step. If there is any good "biological" or "ecological" reason why I shoudn't use the fact value rounded to the highest integer please let me know, as I intend to use it!

**Comment by BrunoVilela** [comment]
Hi Virginia,
thanks for pointing out for this issue. I was not able to reproduce your code, as you do not provide the object 'proj4'. Could you please include it in your code, so I can check the problem?

**Comment by VirginiaMorera** [comment]
Hi @BrunoVilela 
Sorry, I totally forgot about that: proj4 is just a CRS object containing the projection, I've updated my post to include it.

**Comment by BrunoVilela** [comment]
Hi @VirginiaMorera,
You are right, the error occurs because the aggregation factor is not an integer. But, note that rounding the number may be an error, as you will get the central value of the cell that doesn't correspond to the original cell (cell size and position does not match). I will try to work on a solution as soon as possible, but if you come up with anything please let me know. Thanks again!

**Comment by BrunoVilela** [comment]
Hi @VirginiaMorera,
Just noticed that the resample function can do the job alone. So, the better option is to avoid aggregate the rasters if  the factors are not an integer, as we would lost important information for the 'resample' function. I will push the updated function in the next hour to github, after some testing.
Thanks!

**Comment by BrunoVilela** [comment]
Issue fixed. Thanks @VirginiaMorera!

**Comment by VirginiaMorera** [comment]
I've tried it and it works! Thank you very much for fixing it so quickly!
