### ISSUE TITLE
Function lets.iucn fails for species names

### ISSUE THREAD

**Issue by cmzambranat** [macroecology/letsR#5]
Hi,

The function lets.iucn fails to parse for some species.
```
lets.iucn("Abrawayaomys ruschii")
Error: failed to load HTTP resource
```
I double checked the species name at the IUCN red list website and the name is correct.

thanks,

Carlos

**Comment by calebasaraba** [comment]
Hello,

I am having the same problem ~ species names from the IUCN red list don't seem to work with `lets.iucn` function calls, returning `Error: failed to load HTTP resource`.

Thanks!

**Comment by BrunoVilela** [comment]
Hi everyone, sorry for the delay in dealing with this. So, IUCN changed the API of their website and these functions in the package are now breaking. IUCN made clear to me that they prefer people to download the data direct from their website. So, currently the best option to download IUCN data is the package "rredlist" from ROpenSci, but I think you have to obtain a IUCN API token first. Best, Bruno
