### ISSUE TITLE
Mask a PresAbs object instead of cropping?

### ISSUE THREAD

**Issue by maxfarrell** [macroecology/letsR#6]
I am interested in masking rivers and seas from my PresenceAbsence object. 

I see there is a way to crop with lets.pamcrop as outlined in https://rmacroecology.netlify.com/2018/01/24/cropping-and-subseting-your-presence-absence-matrix/, but is there a way to invert this so as to mask a region based on a provided shapefile?

**Comment by BrunoVilela** [comment]
Hi @maxfarrell, there is no such function in the package. But  you can transform the PAM into a shapefile using rasterToPolygons(), and clip your own shapefiles with gIntersection().
