### ISSUE TITLE
I can't install the package 'letsR

### ISSUE THREAD

**Issue by queziaramalho** [macroecology/letsR#7]
Hi, guys,

I'm so interested in the package, but I can't install it. I have the R last version ( 3.6.3). When I try, R gives me this warning message: 
"Warning in install.packages :
 package ‘letsR’ is not available (for R version 3.6.3)"

What I need to do?

Thanks,
Quezia Ramalho

**Comment by fgabriel1891** [comment]
Hi, it worked for me installing the developer version from Github. instructions are in the readme of this repo.

**Comment by fabro** [comment]
Thanks, Gabriel. Yes, the package is not currently on CRAN because of some checking issues but it will be soon. Until then, you need to install the developers version.
