### ISSUE TITLE
Problem with the lets.addvar function

### ISSUE THREAD

**Issue by jpramirez10** [macroecology/letsR#9]
Dear all,

I just wanted to report a small issue I found when using the very useful letsR package. The thing is that using the lets.addvar with the mean or sd function values generate exactly the same results, even if using the example dataset.  I was wondering if there is any mistake in the code that is responsible for this mistake, and if there is anything I would need to change to make this function work properly. I tried to modify the code, but I was not able to make it work as I wanted to.

An example of the runs in which I obtain this unexpected result is the following:

PAM_temp_sd <- lets.addvar(PAM, temp, onlyvar = TRUE, fun=mean)
PAM_temp_mn <- lets.addvar(PAM, temp, onlyvar = TRUE, fun=sd)

PAM_temp_sd-PAM_temp_mn ##gives a value of 0, showing that using fun=mean gives the same result as fun=sd

Best!
Juan

**Comment by BrunoVilela** [comment]
Hi Juan,

Thanks for reporting this issue, in the new version of letsR this issue have been fixed. 

Best
Bruno
